# Generated by Django 5.2.3 on 2025-06-30 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_number', models.CharField(max_length=50, unique=True, verbose_name='通知书编号')),
                ('group_name', models.CharField(max_length=100, verbose_name='所属分组')),
                ('group_teacher', models.CharField(max_length=50, verbose_name='分组教师')),
                ('teacher_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入正确的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='教师联系方式')),
                ('report_location', models.CharField(max_length=200, verbose_name='报到地点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分组信息',
                'verbose_name_plural': '分组信息',
                'ordering': ['group_name', 'notification_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('group_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='groups.groupinfo', verbose_name='分组信息')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='core.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生分组分配',
                'verbose_name_plural': '学生分组分配',
                'ordering': ['-assigned_at'],
                'unique_together': {('student', 'group_info')},
            },
        ),
    ]
