# Generated by Django 5.2.3 on 2025-06-30 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('id_card_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='身份证号码格式不正确', regex='^\\d{17}[\\dX]$')], verbose_name='身份证号')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], editable=False, max_length=1, verbose_name='性别')),
                ('residence_status', models.CharField(choices=[('RESIDENT', '住校'), ('NON_RESIDENT', '不住校')], max_length=20, verbose_name='住校情况')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='体重(kg)')),
                ('uniform_purchase', models.BooleanField(default=False, verbose_name='是否自愿订购校服')),
                ('interests_talents', models.TextField(blank=True, help_text='请详细描述学生的兴趣爱好和特长', verbose_name='兴趣特长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
