# Generated by Django 5.2.3 on 2025-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址'),
        ),
        migrations.AddField(
            model_name='student',
            name='import_batch',
            field=models.CharField(blank=True, max_length=50, verbose_name='导入批次'),
        ),
        migrations.AddField(
            model_name='student',
            name='import_row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='导入行号'),
        ),
        migrations.AddField(
            model_name='student',
            name='info_status',
            field=models.CharField(choices=[('IMPORTED', '已导入'), ('PARTIAL', '部分完成'), ('COMPLETE', '信息完整')], default='IMPORTED', max_length=20, verbose_name='信息完整度'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资料完成时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests_talents',
            field=models.TextField(blank=True, verbose_name='兴趣特长'),
        ),
        migrations.AlterField(
            model_name='student',
            name='residence_status',
            field=models.CharField(choices=[('RESIDENT', '住校'), ('NON_RESIDENT', '不住校'), ('UNKNOWN', '未填写')], default='UNKNOWN', max_length=20, verbose_name='住校情况'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uniform_purchase',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否自愿订购校服'),
        ),
    ]
