# Generated by Django 5.2.3 on 2025-07-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_email_student_import_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notification_number',
            field=models.CharField(default=123, max_length=50, unique=True, verbose_name='通知书编号'),
            preserve_default=False,
        ),
    ]
